package com.prajna.mentor_extension.DTO;

public enum ProjectName {
    ANNUAL_RETURN_APP,
    BUILDOUT_XURL,
    OBJECT_MODELING_V2,
    BUILDOUT_MACHINE_CODING_BIDBLAST,
    BYTES,
    OOP_ENCAPSULATION_JAVA,
    BUILDOUT_MACHINE_CODING_FPL_AUCTION,
    CODING_GAME,
    QCALC_V2,
    BUILDOUT_MACHINE_CODING_JUKEBOX,
    ENCAPSULATION,
    QCONTEST,
    BUILDOUT_MACHINE_CODING_RESTAURANT_RATING,
    INHERITANCE,
    QEATS_SHARED_RESOURCES,
    BUILDOUT_XCOMPANY,
    INTERNALQUES,
    QEATS_V2,
    BUILDOUT_XMEMEJAVA,
    MYSQL,
    QMONEY_V2,
    MYSQL_ADVANCED,
    BUILDOUT_XNEWS,
    BUILDOUT_XQUIZ,
    OBJECT_MODELING;
}